# Generated by Django 5.2.1 on 2025-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.ManyToManyField(to="movies.actor"),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movies.genre"),
        ),
    ]
