# Generated by Django 5.2.1 on 2025-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_cast_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="actors"),
        ),
    ]
