# Generated by Django 5.2.1 on 2025-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_actor_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
